const en = {
    "books": "Книги",
    "children": "Діти",
    "error": "Помилка",
    "failed_to_fetch_books": "Неможливо отримати книги",
    "please_try_again_later": "Будь ласка, спробуйте пізніше",
    "back": "Назад",
    "reading_speed_title": "Швидкість читання",
    "reading_speed_description": "Читай текст вголос. Слова підсвічуватимуться по мірі читання: зелений — правильно, червоний — помилка, сірий — пропущено.",
    "reading_speed_select_child": "Обери профіль дитини, щоб почати",
    "reading_speed_start": "Почати читання",
    "reading_speed_stop": "Зупинити",
    "reading_speed_try_again": "Спробувати ще раз",
    "reading_speed_wpm": "Слів на хвилину",
    "reading_speed_accuracy": "Точність",
    "reading_speed_correct": "Правильних слів",
    "reading_speed_errors": "Помилок",
    "reading_speed_skipped": "Пропущено",
    "microphone_permission_denied": "Для замірювання швидкості читання потрібен доступ до мікрофона",
    "reading_speed_connection_failed": "Не вдалося підключитися. Спробуйте ще раз.",
    "reading_speed_stress_accuracy": "Точність наголосу",
    "reading_speed_stress_processing": "Аналізуємо…",
    "reading_speed_stress_failed": "Не вдалося порахувати",
    "reading_speed_stress_hint": "Результат з'явиться трохи пізніше — можна вийти з екрана, обробка триватиме у фоні.",
    "reading_history_title": "Історія читання",
    "reading_history_empty": "Поки що немає жодної сесії читання",
    "reading_history_fetch_failed": "Не вдалося завантажити історію читання",
    "reading_history_wpm_short": "сл/хв",
    "reading_history_audio_unavailable": "Аудіо для цієї сесії недоступне",
    "reading_history_delete": "Видалити",
    "reading_history_delete_confirm_title": "Видалити цю сесію?",
    "reading_history_delete_confirm_message": "Запис і результати буде видалено назавжди. Це не можна скасувати.",
    "reading_history_delete_failed": "Не вдалося видалити сесію",
    "cancel": "Скасувати",
    "reading_history_select_child": "Оберіть дитину, щоб переглянути історію читання",
    "reading_history_no_children": "Ще немає жодної доданої дитини",
    "failed_to_fetch_children": "Не вдалося отримати список дітей",
    "word_status_legend_title": "Що означають кольори",
    "word_status_correct": "Прочитано правильно",
    "word_status_error": "Прочитано неправильно",
    "word_status_skipped": "Пропущено під час читання",
    "word_status_not_in_vocabulary": "Слово поза словником розпізнавання",
    "word_status_not_reached": "Не встигли дочитати",
    "word_status_stress_error": "Неправильний наголос (підкреслення)",
};

export default en;
